### ISSUE TITLE
bubble chat

### ISSUE THREAD

**Issue by SanskarP1** [MoazSayed7/Flutter-Chat-App-Firebase-Authentication-Messaging-WhatsApp-Like#1]
can you help me with how to make changes or replace bubble chat

**Comment by MoazSayed7** [comment]
### Send message to me.
[My Linkedin](https://www.linkedin.com/in/moazsayed/)

**Comment by SanskarP1** [comment]
im still getting error in version

**Comment by MoazSayed7** [comment]
Message me on LinkedIn

**Comment by SanskarP1** [comment]
please accept in linked in

**Comment by SanskarP1** [comment]
Exception has occurred. StateError (Bad state: cannot get field "version"
on a DocumentSnapshotPlatform which does not exist)
